(function() {var implementors = {};
implementors["themis"] = [{text:"impl&lt;D:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>, E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"themis/secure_message/struct.SecureMessage.html\" title=\"struct themis::secure_message::SecureMessage\">SecureMessage</a>&lt;D, E&gt;",synthetic:false,types:["themis::secure_message::SecureMessage"]},{text:"impl&lt;D:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"themis/secure_message/struct.SecureSign.html\" title=\"struct themis::secure_message::SecureSign\">SecureSign</a>&lt;D&gt;",synthetic:false,types:["themis::secure_message::SecureSign"]},{text:"impl&lt;E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"themis/secure_message/struct.SecureVerify.html\" title=\"struct themis::secure_message::SecureVerify\">SecureVerify</a>&lt;E&gt;",synthetic:false,types:["themis::secure_message::SecureVerify"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"themis/struct.Error.html\" title=\"struct themis::Error\">Error</a>",synthetic:false,types:["themis::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"themis/enum.ErrorKind.html\" title=\"enum themis::ErrorKind\">ErrorKind</a>",synthetic:false,types:["themis::error::ErrorKind"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
