language: rust

sudo: required
dist: trusty
rust: stable

addons:
  apt:
    sources:
    - sourceline: "deb https://pkgs.cossacklabs.com/stable/ubuntu trusty main"
      key_url: "https://pkgs.cossacklabs.com/gpg"
    packages:
    - libthemis-dev

branches:
  except:
  - /^wip\/.*$/

env:
  global:
  - RUSTFLAGS="-D warnings"

install:
- rustup component add clippy-preview
- rustup component add rustfmt-preview
- cargo install cargo-deadlinks

script:
- cargo fmt -- --check
- cargo build
- cargo clippy --all-targets
- cargo test
- cargo clean --doc && cargo doc --no-deps && cargo deadlinks
