language: rust

sudo: required
dist: trusty
rust: stable
cache: cargo

addons:
  apt:
    sources:
    - sourceline: "deb https://pkgs.cossacklabs.com/stable/ubuntu trusty main"
      key_url: "https://pkgs.cossacklabs.com/gpg"
    packages:
    - libthemis-dev

branches:
  except:
  - /^wip\/.*$/

env:
  global:
  - RUSTFLAGS="-D warnings"

jobs:
  include:
  - stage: Static checks
    name: Formatting, code style, doc coverage
    install:
    - rustup component add clippy-preview
    - rustup component add rustfmt-preview
    - cargo deadlinks --version || cargo install cargo-deadlinks
    script:
    - cargo fmt -- --check
    - cargo clippy --all-targets
    - cargo clean --doc && cargo doc --no-deps && cargo deadlinks
  - stage: Running tests
    name: System Themis
    script:
    - cargo build
    - cargo test
  - stage: Running tests
    name: Vendored Themis
    script:
    - cargo build --features "vendored"
    - cargo test --features "vendored"

matrix:
  fast_finish: true
  allow_failures:
    - stage: Running tests
      name: Vendored Themis
