language: rust

sudo: required
dist: trusty
rust: stable
cache: cargo

branches:
  except:
  - /^wip\/.*$/

env:
  global:
  - RUSTFLAGS="-D warnings"

before_install:
- rustup component add clippy-preview
- rustup component add rustfmt-preview
- cargo deadlinks --version || cargo install cargo-deadlinks

jobs:
  include:
  - name: Master Themis
    install:
    - git clone https://github.com/cossacklabs/themis.git /tmp/themis
    - cd /tmp/themis && sudo make install && cd -
    script:
    - cargo fmt -- --check
    - cargo clean --doc && cargo doc --no-deps && cargo deadlinks
    - cargo clippy --all-targets
    - cargo build
    - cargo test
    - LIBTHEMIS_STATIC=1 cargo build
    - LIBTHEMIS_STATIC=1 cargo test
  - name: System Themis
    addons:
      apt:
        sources:
          - sourceline: "deb https://pkgs.cossacklabs.com/stable/ubuntu trusty main"
            key_url: "https://pkgs.cossacklabs.com/gpg"
        packages:
          - libthemis-dev
    script:
    - cargo fmt -- --check
    - cargo clean --doc && cargo doc --no-deps && cargo deadlinks
    - cargo clippy --all-targets
    - cargo build
    - cargo test
    - LIBTHEMIS_STATIC=1 cargo build
    - LIBTHEMIS_STATIC=1 cargo test
  - name: Vendored Themis
    script:
    - cargo clean --doc && cargo doc --features "vendored" && cargo deadlinks
    - cargo clippy --all-targets --features "vendored"
    - cargo build --features "vendored"
    - cargo test --features "vendored"

matrix:
  allow_failures:
  # The latest released version of Themis (0.10) does not include
  # proper pkg-config files so the build is failing for now.
  - name: System Themis
